# Generated by Django 5.2.7 on 2025-10-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('author', 'Author'), ('moderator', 'Moderator'), ('customer', 'Customer'), ('editor', 'Editor')], default='customer', max_length=20),
        ),
    ]
